# ===----------------------------------------------------------------------===
#
# This source file is part of the ASConnectService open source project
#
# Copyright (c) 2025 Röck+Cöde VoF. and the ASConnectService project authors
# Licensed under the EUPL 1.2 or later.
#
# See LICENSE for license information
# See CONTRIBUTORS for the list of ASConnectService project authors
#
# ===----------------------------------------------------------------------===
                    
generate:
    - types
    - client
namingStrategy: defensive
accessModifier: public
